### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by trvrb** [nextstrain/hepatitisB#12]
Can I request that we rename this repo (`hepatitisB`) and rename the currently output Auspice JSON files (`hbv_all.json`, etc...) to match?

1. I think that all pathogen repos should seek to match name of repo to name of Auspice JSON. The outliers here like `seasonal-flu` vs `flu_seasonal_h3n2...` were a mistake.
2. Generally we target the common name of the pathogen instead of the scientific acronym (`ebola` rather than `ebov`, `mpox` rather `mpxv`, `dengue` rather than `denv`, etc...)
3. @jameshadfield: I know it feels more natural coming from primarily JavaScript coding, but I don't like how `hepatitisB` results in a case-sensitive URL (or maybe this just came from Katie's choice for the adaptive-evolution directory). I still find needing to remember that nextstrain.org/wnv doesn't work to be frustrating. I'd keep with our snake-case convention (`nextclade/sars-cov-2`, `north-america`, `zika-tutorial`, `avian-flu`, etc...). This gets a bit more iffy for me with things like `nextclade/sars-cov-2/21L` where without the capitalization it's hard to know what's going on, but I'd stick with lowercase snake-case for the core repo name.

My suggestion would be to use `hepatitis-b` as both repo name and JSON prefix, but I would be okay with `hep-b` as well. Or for hep B in particular, I could also be okay with `hbv` for both repo and JSON prefix (given how common this parlance is, especially when referring to HCV).

**Comment by jameshadfield** [comment]
Repo name changed to `hbv`, which was already the name used for the builds!
